### PR TITLE
Create github actions for maven central publish

### PR DESCRIPTION
**Pull request by rzhang10**

### CODE REVIEW

**Review by aastha25 — COMMENTED** [review]
have you tested these changes @rzhang10 ?
and could you confirm if we use java 8/11 for building linkedin-calcite?

**Comment by ljfgem** [comment]
+1 to @aastha25, @rzhang10 could you update the PR description to include the test done?

**Comment by ljfgem** [comment]
> +1 to @aastha25, @rzhang10 could you update the PR description to include the test done?

@rzhang10 could you please add the test done? It would be great if this PR could be merged before #86

**Comment by rzhang10** [comment]
> > +1 to @aastha25, @rzhang10 could you update the PR description to include the test done?
> 
> @rzhang10 could you please add the test done? It would be great if this PR could be merged before #86

Yes, I plan to use a empty commit to trigger build with this github action and see if it publish successfully.

**Comment by rzhang10** [comment]
I think there's no good way to test "github actions" before they are merged.. so i think we can check in now and see if it can successfully publish. whether it succeed or not itself serves as a test.

I  don't think there's a risk since this doesn't touch any code.

**Review by aastha25 — APPROVED** [review]
LGTM, lets merge to enable testing

**Comment by rzhang10** [comment]
https://github.com/linkedin/linkedin-calcite/commit/2500b128456bd67179e3642fe32d0d24407d365d this is the final rebased commit.

**Pull request merged**
