### PR TITLE
Shade more dependencies

### PR DESCRIPTION
**Pull request by findepi**
Before

```
$ jar tf ~/.m2/repository/com/linkedin/calcite/calcite-core/1.21.0.140/calcite-core-1.21.0.140-shaded.jar | cut -d/ -f -3 | sort | uniq -c | sort -rn
   4746 com/linkedin/coral
   3772 org/apache/calcite
    504 org/apache/commons
    463 org/codehaus/janino
    238 org/yaml/snakeyaml
    205 com/yahoo/sketches
    187 com/jayway/jsonpath
     32 org/codehaus/commons
     15 com/yahoo/memory
...
```

After, with `shaded-all` artifact
```
$ jar tf core/target/calcite-core-*-shaded-all.jar | cut -d/ -f -3 | sort | uniq -c | sort -rn
   6394 com/linkedin/coral
   3772 org/apache/calcite
     10 META-INF/maven/com.fasterxml.jackson.core
      7 META-INF/maven/org.codehaus.janino
      7 META-INF/maven/org.apache.httpcomponents
      7 META-INF/maven/org.apache.commons
      7 META-INF/maven/org.apache.calcite.avatica
      7 META-INF/maven/com.yahoo.datasketches
      7 META-INF/maven/com.linkedin.calcite
      4 META-INF/maven/org.yaml
      4 META-INF/maven/org.slf4j
      4 META-INF/maven/net.hydromatic
      4 META-INF/maven/commons-logging
      4 META-INF/maven/commons-lang
      4 META-INF/maven/commons-codec
      4 META-INF/maven/com.google.protobuf
      4 META-INF/maven/com.google.guava
      4 META-INF/maven/com.google.code.findbugs
      4 META-INF/maven/com.fasterxml.jackson.dataformat
      4 META-INF/maven/com.esri.geometry
      1 responses.proto
      1 requests.proto
      1 org/apache/
      1 org/
      1 org.codehaus.commons.compiler.properties
      1 org-apache-calcite-jdbc.properties
      1 common.proto
      1 com/linkedin/
      1 com/
      1 codegen/templates/Parser.jj
      1 codegen/templates/
      1 codegen/includes/parserImpls.ftl
      1 codegen/includes/compoundIdentifier.ftl
      1 codegen/includes/
      1 codegen/config.fmpp
      1 codegen/
      1 META-INF/services/java.sql.Driver
      1 META-INF/services/com.fasterxml.jackson.core.ObjectCodec
      1 META-INF/services/com.fasterxml.jackson.core.JsonFactory
      1 META-INF/services/
      1 META-INF/maven/
      1 META-INF/git.properties
      1 META-INF/NOTICE.txt
      1 META-INF/NOTICE
      1 META-INF/MANIFEST.MF
      1 META-INF/LICENSE.txt
      1 META-INF/LICENSE
      1 META-INF/DEPENDENCIES
      1 META-INF/
```

Relates to: https://github.com/prestosql/presto/issues/5604

### CODE REVIEW

**Comment by findepi** [comment]
@laurachenyu is this the right target branch?

cc @phd3 @vgkholla

**Comment by laurachenyu** [comment]
@findepi yes, ~/.m2/repository/com/linkedin/calcite/calcite-core/1.21.0.140/calcite-core-1.21.0.140-shaded.jar

**Comment by findepi** [comment]
Perfect. This is ready to review then.

**Comment by phd3** [comment]
@funcheetah would you be able to help with the review of this PR?

**Comment by findepi** [comment]
@funcheetah is this the right target branch?

**Comment by findepi** [comment]
cc @wmoustafa

**Comment by funcheetah** [comment]
Thanks @findepi for submitting this patch. This is the right branch. Considering the potential impact for downstream consumers, we'd like to evaluate and test this patch before merging.

**Comment by findepi** [comment]
Thanks for the update @funcheetah.

**Comment by wmoustafa** [comment]
@findepi Could you clarify how the lack of this patch currently impacts Presto's integration with Coral? (updating both the PR and the [issue](https://github.com/prestosql/presto/issues/5604) descriptions with this info would be quite helpful).

**Comment by wmoustafa** [comment]
Also, @findepi has this been tested with Presto (this involves depending on this from Coral, then depending on Coral from Presto, and testing)? @funcheetah, I remember some of those dependencies were intentionally not shaded?

**Comment by findepi** [comment]
I added the info about impact to the issue https://github.com/prestosql/presto/issues/5604

> This doesn't cause a problem today, but will cause a problem as soon as we want to use anything depending (directly or transitively) on these not-properly-shaded libraries.

**Comment by findepi** [comment]
Any updates here?

**Comment by wmoustafa** [comment]
@findepi We have not tested this patch internally yet. Are you able to test it with Presto? (As I mentioned by building both Coral and Presto using it).

**Comment by findepi** [comment]
The master branch does not build locally for me
```
$ ./mvnw -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /Users/findepi/.m2/wrapper/dists/apache-maven-3.5.4-bin/4lcg54ki11c6mp435njk296gm5/apache-maven-3.5.4
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Default locale: en_PL, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

```
$ ./mvnw clean install -DskipTests
...
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.498 s
[INFO] Finished at: 2020-11-24T08:38:42+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project calcite-linq4j: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - /Users/findepi/repos/linkedin-calcite/linq4j/src/main/java/org/apache/calcite/linq4j/Enumerator.java:109: error: header used out of sequence: <H4>
[ERROR]    * <h4>Notes to Implementers</h4>
[ERROR]      ^
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/findepi/repos/linkedin-calcite/linq4j/target/apidocs' dir.
[ERROR] 
```

I can build the project with `-Dmaven.javadoc.skip=true` though and Presto builds perfectly fine then.


BTW, any reason to use non-SNAPSHOT maven version during development?

**Comment by wmoustafa** [comment]
Thanks for reporting this! @funcheetah is this expected?

We use Coral with Spark, Pig, and MapReduce. I will test this internally with those engines to make sure those new shading rules do not break other Coral usages.

**Comment by findepi** [comment]
@wmoustafa any progress here?

**Comment by wmoustafa** [comment]
@findepi apologies for the delay. It is just that this patch is highly impactful in terms of the change and the number of dependencies that can be affected by it in unexpected ways, where the issue will only come up if a specific code path that is affected by the additional shading is exercised. That said, I was thinking we could keep the original configuration intact, and add a new one specifically for Presto. So essentially we publish two jars, one partially shaded and one fully shaded, but keep the classifier as is for the partially shaded (current) one. Would that work?

**Comment by findepi** [comment]
There already is `<classifier>shaded</classifier>` in use, so it's not affecting "all users" of the library and you're already publishing two jars.
Whether you want to keep this, reduce to one jar, or publish three jars -- that's not my call.

Also, some dependencies were shaded and some were not. I did not find a code comment informing why, so i assume this could be an omission.
The change does shade those "missing" dependencies. I don't understand why this is impactful.

I understand you're concerned that this may cause problems so some project downstream.
If they are relying on dependencies that will now be shaded, they can just these dependencies explicitly, right?

**Comment by wmoustafa** [comment]
@findepi I actually meant that `<classifier>shaded</classifier` is the one being used by other downstream applications. Sorry for the confusion. I was also suggesting if we create a third classifier, like `<classifier>shaded-all</classifier>`.

**Comment by findepi** [comment]
Thanks for the clarification. Not my call, I will defer to project's maintainers.

**Comment by wmoustafa** [comment]
@findepi, please make the change and I will approve the PR.

**Comment by findepi** [comment]
updated & rebased

**Comment by findepi** [comment]
@wmoustafa did i get this right this time?

**Comment by wmoustafa** [comment]
For now, could you please not relocate the classes in the `shaded` jar and still use the old relocation prefix? Feel free to use a new relocation pattern for the `shaded-all` jar. Looks good otherwise.

**Comment by findepi** [comment]
it seems you're in a better position to fix the incorrect shading.

**Pull request closed without merging**
